server:
  port: 8082

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'


spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: com.umasuo.database.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: QWERTYUIOPASDFGHJKLZXCVBNM
  expires: 72000

sms:
  yunpian:
    key: just test value