server:
  port: 8809

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'


spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: com.umasuo.database.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379

jwt:
  secret: QWERTYUIOPASDFGHJKLZXCVBNM
  expires: 72000000

sms:
  yunpian:
    key: id

device:
  service:
    url: http://localhost:8806/devices/